package com.himataku.atomicreate.register;

import java.util.List;

/** Master list of metals registered in raw/crushed/nugget/ingot/sheet form. */
public final class Metals {
    private Metals() {}

    public static final List<String> ALL = List.of(
            "lithium",
            "beryllium",
            "boron",
            "carbon",
            "sodium",
            "magnesium",
            "aluminium",
            "silicon",
            "phosphorus",
            "sulfur",
            "potassium",
            "calcium",
            "scandium",
            "titanium",
            "vanadium",
            "chromium",
            "manganese",
            //"iron",
            "cobalt",
            "nickel",
            //"copper",
            //"zinc",
            "gallium",
            "germanium",
            "arsenic",
            "selenium",
            "rubidium",
            "strontium",
            "yttrium",
            "zirconium",
            "niobium",
            "molybdenum",
            "technetium",
            "ruthenium",
            "rhodium",
            "palladium",
            "silver",
            "cadmium",
            "indium",
            "tin",
            "antimony",
            "tellurium",
            "iodine",
            "cesium",
            "barium",
            "lanthanum",
            "cerium",
            "praseodymium",
            "neodymium",
            "promethium",
            "samarium",
            "europium",
            "gadolinium",
            "terbium",
            "dysprosium",
            "holmium",
            "erbium",
            "thulium",
            "ytterbium",
            "lutetium",
            "hafnium",
            "tantalum",
            "tungsten",
            "rhenium",
            "osmium",
            "iridium",
            "platinum",
            //"gold",
            "mercury",
            "thallium",
            "lead",
            "bismuth",
            "polonium",
            "astatine",
            "francium",
            "radium",
            "actinium",
            "thorium",
            "protactinium",
            "uranium",
            "neptunium",
            "plutonium",
            "ununminecraftium"
    );
}